import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
//import { Rating } from '@mui/material'
//import AccessAlarmIcon from '@mui/icons-material/AccessAlarm';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Present Live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <AccessAlarmIcon/> */}
      {/* <Rating name="half-rating" defaultValue={2.5} precision={0.5} /> */}
      {/* <Rating name="half-rating-read" defaultValue={2.5} precision={0.5} readOnly /> */}
        <h1 className='text-3xl font-bold underline'>
          Welcome
        </h1>
        <p>Present-live</p>
      </main>
    </div>
  )
}

export default Home
